import sys
from random import randint, seed

sys.setrecursionlimit(50)

# do not edit this file
# use pdb: https://docs.python.org/3/library/pdb.html
# what is the value of x[451] before the program crashes?
# some useful commands: p, bt, ll, n, s, interact, c, up


def ping(x):
    x[randint(0, 1023)] = randint(0, 1023)
    pong(x)


def pong(x):
    x[randint(0, 1023)] = randint(0, 1023)
    ping(x)


if __name__ == "__main__":
    seed(42)
    ping({})