# do not edit this file


def check1(s):
    if len(s) > 20:
        return False
    if len(s) < 5:
        return False
    if len(s) < 12:
        return False
    return check2(s)


def check2(s):
    if s[5] != "o":
        return False
    if s[10] != "o":
        return False
    if s[15] != "o":
        return False
    return check3(s)


def check3(s):
    if s[0] == "a":
        return check4(s)
    return check5(s)


def check4(s):
    if len(s) < 14:
        return False
    return True


def check5(s):
    if s[3:7] == "bbob":
        return False
    if s[3:7] == "baob":
        return True
    return False


if __name__ == "__main__":
    s = "yvjbaobulion123o"
    if not check1(s):
        print("NO")
        exit(1)
    print("YES")